# Generated by Django 5.2.10 on 2026-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_pdf_file_alter_invoice_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='issued_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
