# Generated by Django 5.2.10 on 2026-03-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('package_type', models.CharField(choices=[('umrah', 'Umrah'), ('hajj', 'Hajj'), ('holiday', 'Holiday')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_group_package', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_with_bed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_without_bed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('infant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='packages.package')),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
    ]
