# Generated by Django 5.2.10 on 2026-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
